# Generated by Django 3.0.2 on 2020-01-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
